### ISSUE TITLE
fqn contains a port number

### ISSUE THREAD

**Issue by bembudo** [KKDad/piwigo-ruby#6]
How do i enter a port number?

I get the error below

``check_host': bad component(expected host component): [localhost:8083] (URI::InvalidComponentError)`

**Comment by KKDad** [comment]
Hello Bembudo - 

Your right! I tried it out and you are correct, you were not able to specify a port. 

I've pushed an update to the gem that corrects this. Please try again with version [0.6.0](https://rubygems.org/gems/piwigo-api/versions/0.6.0). I added an example [here](https://github.com/KKDad/piwigo-api/blob/master/examples/Different_Port.md) showing the usage.

Thanks,
Adrian

**Comment by bembudo** [comment]
that works thank you @KKDad  much appreciated

quick question, does the API support adding an image to an existing album  ?

**Comment by KKDad** [comment]
Yes it does, you should be able to write a script that looks up the album like this:
~~~
  album = Piwigo::Albums.lookup(@session, 'Album name')
~~~

Adding it to the other example:
~~~
require 'piwigo/session'
require 'piwigo/images'
require 'piwigo/albums'

session = Piwigo::Session.login('localhost', 'root', 'piwigo', port: 8083, https: false)
unless session.nil?

  # Look to see if we have previously created an Album in Piwigo with this name
  album = Piwigo::Albums.lookup(@session, 'Chippy')
  if album.nil?
    album = Piwigo::Albums::Album.new
    album.name = 'Chippy Pics'
    album = Piwigo::Albums.add(session, album)
  end

  filename = 'C:\Photos\chippy.jpg'
  if Piwigo::Images.lookup(session, filename).nil?
    puts 'Uploading'
    Piwigo::Images.upload(session, filename, album, 'puppy')
  end
end
~~~
